services:
  flagexplorerapp.api:
    image: ${DOCKER_REGISTRY-}flagexplorerappapi
    build:
      context: .
      dockerfile: FlagExplorerApp.Api/Dockerfile

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    networks:
      - flagexplorer-network

networks:
  flagexplorer-network:
    driver: bridge