services:  
 flagexplorerapp.api:  
   environment:  
     - ASPNETCORE_ENVIRONMENT=Development  
     - ASPNETCORE_HTTP_PORTS=8080  
     - ASPNETCORE_HTTPS_PORTS=8082  
     - CosmosDb__AccountEndpoint=https://cosmosdb:8081/  
     - CosmosDb__AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRp0EJg==  
     - CosmosDb__DatabaseName=FlagExplorerDb  
   ports:  
     - "8080:8080"  
     - "8082:8082"  
   volumes:  
     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro  
     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro  
   networks:  
     - flagexplorer-network  

 cosmosdb:  
   image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator  
   environment:  
     - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3  
     - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true  
     - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1  
     - AZURE_COSMOS_EMULATOR_NO_SSL=true
   ports: 
     - "8081:8081" # Added to expose the Cosmos DB endpoint 
     - "10250:10250"  
     - "10251:10251"  
     - "10252:10252"  
     - "10253:10253"  
     - "10254:10254"  
   networks:  
     - flagexplorer-network  
   volumes:  
     - cosmosdbdata:/data  

networks:  
 flagexplorer-network:  
     driver: bridge  

volumes:  
 cosmosdbdata: