name: FlagExplorerApp.Api  Pipeline  

on:
  push:
    branches: '**'
  pull_request:
    branches: [master]

jobs:  
 build:  
   name: Build and Push Docker Image  
   runs-on: ubuntu-latest  
   defaults:
      run:
        working-directory: FlagExplorerApp.API
   steps:  
   - name: Checkout Code  
     uses: actions/checkout@v3  

   - name: Setup .NET  
     uses: actions/setup-dotnet@v3  
     with:  
       dotnet-version: '8.x'  

   - name: Build Application  
     run: |  
      cd /home/runner/work/FlagExplorerApp/FlagExplorerApp.API  
      dotnet build --configuration Release    

   - name: Log in to Container Registry  
     run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin  

   - name: Build and Push Docker Image  
     run: |  
       docker build -t ${{ secrets.CONTAINER_REGISTRY }}/flagexplorerapp:${{ github.run_id }} .  
       docker push ${{ secrets.CONTAINER_REGISTRY }}/flagexplorerapp:${{ github.run_id }}  

 test:  
   name: Run Tests  
   runs-on: ubuntu-latest  
   needs: build  

   steps:  
   - name: Checkout Code  
     uses: actions/checkout@v3  

   - name: Setup .NET  
     uses: actions/setup-dotnet@v3  
     with:  
       dotnet-version: '8.x'  

   - name: Run Unit Tests  
     run: dotnet test --configuration Release --no-build --filter "Category=Unit"  

   - name: Run Integration Tests  
     run: dotnet test --configuration Release --no-build --filter "Category=Integration"  