name: FlagExplorerApp.Api CI/CD

on:
  push:
    branches: '**'
  pull_request:
    branches: [master]

jobs:
  cosmosdb-emulator:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: FlagExplorerApp

      - name: Debug File Paths
        run: ls -R FlagExplorerApp

      - name: Build Cosmos DB Emulator Docker Image
        working-directory: FlagExplorerApp/FlagExplorerApp.Api
        run: docker build -t cosmosdb-emulator -f Dockerfile.cosmosdb .

      - name: Run Cosmos DB Emulator
        run: docker run -d --name cosmosdb-emulator-container -p 8081:8081 cosmosdb-emulator

  build:
    needs: cosmosdb-emulator  # Ensure build waits for Cosmos DB Emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Dependencies
        run: dotnet restore FlagExplorerApp.sln

      - name: Build Application
        run: dotnet build FlagExplorerApp.sln --no-restore

      - name: Run Unit Tests
        env:
          NUnit_DisableRegistry: "true"
          DOTNET_TEST_ADAPTER_PATH: "./packages/NUnit3TestAdapter.4.2.0/tools"
        run: dotnet test FlagExplorerApp.sln --no-build -v normal --logger:"console;verbosity=detailed"

      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t flagexplorerapp-api -f FlagExplorerApp.Api/Dockerfile .

      - name: Run Docker Container
        run: docker run --platform linux/amd64 -d --name flagexplorerapp-api-container -p 8081:8081 flagexplorerapp-api

      - name: Validate API Endpoints
        run: curl http://localhost:8081/api/health || exit 1