name: FlagExplorerApp.Api  Pipeline  

on:
  push:
    branches: '**'
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
    - name: Build and Run Docker Image
      working-directory: ./FlagExplorerApp
      run: |
      docker build -t flagexplorerapp-api -f Dockerfile .
      docker run -d --name flagexplorerapp-api-container -p 8080:80 flagexplorerapp-api
    - name: Restore dependencies
      run: dotnet restore FlagExplorerApp.sln
    - name: Build
      run: dotnet build FlagExplorerApp.sln --no-restore
    - name: Test
      run: dotnet test FlagExplorerApp.sln --no-build -v normal --logger:"trx"